from build import build_app
Import('env')

cxxfile = ['ex11.cpp']

fortranfile = ['ex12f.f90']

program_inc = []
program_libs = ['unap', 'stdc++']

if env['PLATFORM'] == 'windows':
    program_libs.append(['mpi', 'fmpich2g'])

build_app(env,
          target='ex11',
          sources=cxxfile,
          program_inc=program_inc,
          program_libs=program_libs,
          linker=env['CXX_LINKER'])

# if env['PLATFORM'] == 'windows':
#     program_libs.append('fmpich2g')
# program_libs.append('msmpifec')
# program_libs.append('msmpifmc')
build_app(env,
          target='ex12f',
          sources=fortranfile,
          program_inc=program_inc,
          program_libs=program_libs,
          linker=env['F_LINKER'])
