from build import add_source_files, cxx_source_files

cxxfiles = [
    'unapMatrixAgglomeration.cpp', 'unapMatrixPrecond.cpp',
    'unapMatrixSolver.cpp', 'unapMatrixTest.cpp',
    'eigenvalue/eigenDiagPCG/eigenDiagPCG.cpp', 'interfaces/interfaces.cpp',
    'interfaces/labelPair/labelPair.cpp', 'interfaces/patch/patch.cpp',
    'lduMatrix/lduMatrix.cpp', 'lduMatrix/lduMatrixSpMV.cpp',
    'lduMatrix/lduAgglomeration/lduAgglomerate.cpp',
    'lduMatrix/lduAgglomeration/lduAgglomerateMatrix.cpp',
    'lduMatrix/lduAgglomeration/lduAgglomeration.cpp',
    'lduMatrix/lduAgglomeration/lduAgglomerationAddressing.cpp',
    'lduMatrix/lduAgglomeration/lduAgglomerationCombineLevels.cpp',
    'lduMatrix/lduAgglomeration/lduAgglomerationReorder.cpp'
]

add_source_files(cxxfiles, cxx_source_files)
