import GLOVAR as gl

cxxfile = ['unapMatrixAgglomeration.cpp',
		   'unapMatrixPrecond.cpp',
		   'unapMatrixSolver.cpp',
		   'unapMatrixTest.cpp',
		   'eigenvalue/eigenDiagPCG/eigenDiagPCG.cpp',
		   'interfaces/interfaces.cpp',
		   'interfaces/labelPair/labelPair.cpp',
		   'interfaces/patch/patch.cpp',
		   'lduMatrix/lduMatrix.cpp',
		   'lduMatrix/lduMatrixSpMV.cpp',
		   'lduMatrix/lduAgglomeration/lduAgglomerate.cpp',
		   'lduMatrix/lduAgglomeration/lduAgglomerateMatrix.cpp',
		   'lduMatrix/lduAgglomeration/lduAgglomeration.cpp',
		   'lduMatrix/lduAgglomeration/lduAgglomerationAddressing.cpp',
		   'lduMatrix/lduAgglomeration/lduAgglomerationCombineLevels.cpp',
		   'lduMatrix/lduAgglomeration/lduAgglomerationReorder.cpp'
		  ]

gl.add_files(cxxfile)
