from build import add_source_files, cxx_source_files

cxxfiles = ['lduPreconditioners/lduDiagonal/lduDiagPrecond.cpp',
		    'lduPreconditioners/lduDIC/lduDICPrecond.cpp',
		    'lduPreconditioners/lduDILU/lduDILUPrecond.cpp'
		   ]

add_source_files(cxxfiles, cxx_source_files)
