from build import add_source_files, cxx_source_files

cxxfiles = ['lduSmoothers/lduGaussSeidelSmoother/lduGaussSeidelSmoother.cpp',
		    'chebySmoother/chebySmoother.cpp'
		   ]

add_source_files(cxxfiles, cxx_source_files)
