# -*- mode: python -*-

import os
import utils
from build import build_lninclude, build_lib, cxx_source_files, chost_source_files, cslave_source_files, cxxhost_source_files, build_object

Import('env')

target = 'unap'

subdirs = Split("""
    base
    matrix
    preconditioners
    smoothers
    solvers
    tools
""")

src_include = list(build_lninclude(env))

for d in subdirs:
    SConscript(os.path.join(d, 'SConscript'), exports=['env', 'src_include'])

program_inc = ['/home/export/online3/amd_dev1/guhf/utilities_dev/install/linux64icpcDPOpt/include']
program_libs = []
objs_all = []

source_files = cxx_source_files

if env['PLATFORM'] == 'sw':
    if env['ATHREAD']:
        program_inc += []
        objs_all = objs_all + build_object(env,
                                           sources=chost_source_files,
                                           program_inc=program_inc,
                                           program_libs=program_libs,
                                           sources_type='host')

        objs_all = objs_all + build_object(env,
                                           sources=cslave_source_files,
                                           program_inc=program_inc,
                                           program_libs=program_libs,
                                           sources_type='slave')

        objs_all = objs_all + build_object(env,
                                           sources=cxxhost_source_files,
                                           program_inc=program_inc,
                                           program_libs=program_libs)

objs_all = objs_all + build_object(env,
                                   sources=cxx_source_files,
                                   program_inc=program_inc,
                                   program_libs=program_libs)

build_lib(env,
          target=target,
          sources=objs_all,
          program_inc=program_inc,
          program_libs=program_libs)
