from build import add_source_files, cxx_source_files

cxxfiles = ['MG/MG.cpp',
		    'MG/MGSolve.cpp',
		    'MG/scalingFactor.cpp',
		    'MG/solveCoarsestLevel.cpp',
		    'MG/Vcycle.cpp',
		    'PBiCGStab/PBiCGStab.cpp',
		    'PCG/PCG.cpp'
		   ]

add_source_files(cxxfiles, cxx_source_files)
