# -*- mode: python -*-

from build import add_source_files, cxx_source_files

cxxfiles = Split("""
unap.cpp
vectors/unapVectorOperations.cpp
mpi/unapMPI.cpp
""")

add_source_files(cxxfiles, cxx_source_files)